### ISSUE TITLE
Doesn't inject on restart

### ISSUE THREAD

**Issue by PnsDev** [Vap0r1ze/vpc-shiki#6]
The title says it all (you have to turn it off and on)

**Comment by Vap0r1ze** [comment]
just to make sure, by "restart" you mean closing and reopening discord (or refreshing)?

**Comment by PnsDev** [comment]
Yeah, that and also CTRL + R

**Comment by Vap0r1ze** [comment]
can you make sure that switching between channels doesn't fix it, also check the console for errors if any

**Comment by PnsDev** [comment]
After some inspecting within the console, the plugin isn't loading when discord restart. Trying to unload it throws the following error:
`[Powercord] Tried to unload a non loaded plugin ([object Object])`
After loading it by turning the plugin off and on, the "Plugin loaded" message comes up for the first time and the error stated above no longer occurs.

**Comment by Vap0r1ze** [comment]
ah i see, my plugin tries to unload the default codeblocks plugin on startup. wasn't aware that it threw an error when it was already disabled. I'll be working on a fix for this today.

**Comment by Vap0r1ze** [comment]
Fixed by 456c39f

**Comment by PnsDev** [comment]
Hey the issue is still occurring after updating to 456c39f

**Comment by Vap0r1ze** [comment]
@PnsDev can you screenshot what the error looks like now

**Comment by PnsDev** [comment]
Still the same errors when unloading and loading after a restart. Nothing relating to the plugin comes up on start which makes me feel like it's not starting alongside powercord.

**Comment by Vap0r1ze** [comment]
Just to double check, please run `git rev-parse --short HEAD` in the plugin directory, and attach a *screenshot* the error for me, along with the output of the former command.

**Comment by Vap0r1ze** [comment]
Update:

> [Powercord] Tried to unload a non loaded plugin ([object Object])

This actually never was a breaking issue and happens with everyone. Your issue must have a different cause. Try searching for another error?

**Comment by Vap0r1ze** [comment]
Closing this due to inactivity
